name: victor_vaz_portfolio
description: "Conheça-me através de meu website."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  url_launcher: ^6.3.1
  visibility_detector: ^0.4.0+2
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/victorvaz.webp
    - assets/images/github-logo.svg
    - assets/images/linkedin-logo.svg
